### ISSUE TITLE
to_fr is not applicable method for 'dataframe', 'tbl_df', 'tbl', 'data.frame'

### ISSUE THREAD

**Issue by GuyliannEngels** [SciViews/form.io#1]
When I run the chunks of form.io_test.Rmd, I have an error. The function to_fr is not applicable for several objects : 'dataframe', 'tbl_df', 'tbl', 'data.frame',... (line 37)

**Comment by phgrosjean** [comment]
Update *not* done correctly: `to_fr()` is renamed `rephrase()` in current version. Delete \R\form.io.R`, restart R and retry...

**Comment by GuyliannEngels** [comment]
I delete  R/form.io.R, restart R and retry ... But the error persists. You use to_fr in form.io.R (line 98)

**Comment by phgrosjean** [comment]
Was not latest version. Should be solved now.
